# Generated by Django 5.0.6 on 2024-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_propertytypename_properttype_property_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properttype',
            name='property_type_Name',
        ),
        migrations.AddField(
            model_name='properttype',
            name='property_type',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
