# Generated by Django 5.0.6 on 2024-06-28 18:08

import address.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('base', '0005_remove_properttype_property_type_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertType',
            new_name='PropertyType',
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('Av', 'Available'), ('Oc', 'Occupied'), ('UR', 'Under Renovation')], default='Av', max_length=2)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.propertytype')),
            ],
        ),
    ]
