# Generated by Django 5.0.6 on 2024-06-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_properttype_propertytype_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name_plural': 'Properties'},
        ),
    ]
