# Generated by Django 5.0.6 on 2024-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_property_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Under Renovation', 'Under Renovation')], default='Av', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Property Manager', 'Property Manager')], max_length=20),
        ),
    ]
