# Generated by Django 5.0.6 on 2024-07-02 10:44

import address.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('base', '0010_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
