# Generated by Django 5.0.6 on 2024-07-02 14:56

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_property_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Property Manager', 'Property Manager')], default='Tenant', max_length=20),
        ),
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personal_details', models.JSONField()),
                ('business_details', models.JSONField()),
                ('declaration', models.JSONField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('otp', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('otp_expiry', models.DateTimeField(default=datetime.datetime(2024, 7, 2, 15, 6, 50, 872291, tzinfo=datetime.timezone.utc))),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.property')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start', models.DateTimeField()),
                ('lease_end', models.DateTimeField()),
                ('lease_status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_leased', to='base.property', verbose_name='Property Leased')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant'],
            },
        ),
    ]
