# Generated by Django 5.0.6 on 2024-07-02 15:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_user_role_rentalapplication_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tenant'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 15, 19, 27, 357838, tzinfo=datetime.timezone.utc)),
        ),
    ]
