# Generated by Django 5.0.6 on 2024-07-13 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_user_first_time_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 11, 21, 26, 595918, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='lease_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='Active', max_length=20),
        ),
    ]
