# Generated by Django 5.0.6 on 2024-07-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_maintenancerequest_schedule_date_alter_tenant_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['status', 'schedule_date']},
        ),
    ]
