# Generated by Django 5.0.6 on 2024-07-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
